syntax = "proto3";

package zmk.sensors;

message Request {
    oneof request_type {
        GetSensorBindingRequest get_sensor_binding = 1;
        SetSensorBindingRequest set_sensor_binding = 2;
    }
}

message Response {
    oneof response_type {
        SensorBinding get_sensor_binding = 1;
        SetSensorBindingResponse set_sensor_binding = 2;
    }
}

message Notification {
    oneof notification_type {
        bool unsaved_changes_status_changed = 1;
    }
}

message GetSensorBindingRequest {
    uint32 layer_id = 1;
    int32 sensor_index = 2;
}

message SetSensorBindingRequest {
    uint32 layer_id = 1;
    int32 sensor_index = 2;

    SensorBinding binding = 3;
}

message SensorBinding {
    sint32 computed_behavior_id = 1;
    sint32 behavior_id = 2;
    uint32 param1 = 3;
    uint32 param2 = 4;
}

enum SetSensorBindingResponse {
    SET_SENSOR_BINDING_RESP_OK = 0;
    SET_SENSOR_BINDING_RESP_INVALID_INDEX = 1;
    SET_SENSOR_BINDING_RESP_INVALID_BEHAVIOR = 2;
    SET_SENSOR_BINDING_RESP_INVALID_PARAMETERS = 3;
}